development:
  access_key_id: AKIAJ4DV2JSOSNOBJFNA
  secret_access_key: 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

staging:
  access_key_id: AKIAJ4DV2JSOSNOBJFNA
  secret_access_key: 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

production:
  access_key_id: AKIAJ4DV2JSOSNOBJFNA
  secret_access_key: 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
